### ISSUE TITLE
Fully Connected Hidden Layer 2

### ISSUE THREAD

**Issue by lzhengchun** [tjvandal/deepsd#6]
i saw that you have a `Fully Connected Hidden Layer 2` in the image (figure 2 in the paper), but section 5.1 did not mention it. i also did not see the implementation of the Fully connected layer. did you really use it, or it is a mistake in the figure?

**Comment by tjvandal** [comment]
Layer 2 uses a 1x1 convolutions. In early versions of the paper we used the term fully connected layer for 1x1 convolutions but this is not the correct terminology. This mistake was fixed in the camera ready version, which it seems I never updated on arxiv.  https://dl.acm.org/doi/pdf/10.1145/3097983.3098004

**Comment by lzhengchun** [comment]
oh, i see. thanks very much for your response.
